---
- hosts: all
  become: yes
  
  tasks: 
    - name: install httpd  on linux 
      yum: name=httpd state=present 

 

      when: ansible_os_family == "RedHat" 

    - name: install apache2 on ubuntu 

      apt:  name=apache2  state=present 

    - name: USING CURL 
      command: curl localhost  
      register: data 

      when: ansible_os_family == "Debian"

    - debug: 
        msg: "{{data}}"
